name: lanit
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py39h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022a=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - cycler==0.11.0
    - dominate==2.7.0
    - fonttools==4.37.1
    - ftfy==6.1.1
    - imageio==2.21.2
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - munch==2.5.0
    - networkx==2.8.6
    - numpy==1.23.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pillow==9.2.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.3.0
    - regex==2022.9.11
    - scikit-image==0.19.3
    - scipy==1.9.1
    - six==1.16.0
    - tifffile==2022.8.12
    - torch==1.10.1+cu111
    - torchaudio==0.10.1+rocm4.1
    - torchvision==0.11.2+cu111
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - wcwidth==0.2.5
prefix: /home/cvlab06/.conda/envs/lanit
